version: '3.8'

services:
  logging-service: 
    image: logging-service
    build:
      context: LoggingService
      dockerfile: DockerFile
    ports:
      - "8081:80"
    environment:
      - ConnectionStrings__AdminConnectionString=Host=db;Database=postgres;Username=postgres;Password=postgres
      - ConnectionStrings__LogConnectionString=Host=db;Database=LoggingDB;Username=postgres;Password=postgres
      - ConnectionStrings__HangFireConnectionString=Host=db;Database=HangFireLoggingDB;Username=postgres;Password=postgres
      - RabbitMQConfig__Host=rabbitmq
      - RabbitMQConfig__Username=guest
      - RabbitMQConfig__Password=guest
      - SeqUrl=http://seq:5341

    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5342:5341"
      - "8082:80"
    volumes:
      - seqdata:/data:z

volumes:
  db_data:
  seqdata:




