CREATE DATABASE LoggingDB;
GO
CREATE DATABASE HangFireLoggingDB;
GO

USE HangFireLoggingDB;
ALTER AUTHORIZATION ON DATABASE::HangFireLoggingDB TO sa;
GO
USE LoggingDB;
ALTER AUTHORIZATION ON DATABASE::LoggingDB TO sa;
GO