 CREATE DATABASE LoggingDB;
GO
CREATE DATABASE HangFireLoggingDB;
GO

 ALTER DATABASE LoggingDB SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE HangFireLoggingDB SET READ_COMMITTED_SNAPSHOT ON;
GO

 USE HangFireLoggingDB;
ALTER AUTHORIZATION ON DATABASE::HangFireLoggingDB TO sa;
GO
USE LoggingDB;
ALTER AUTHORIZATION ON DATABASE::LoggingDB TO sa;
GO